require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "c",
    "cpp",
    "css",
    "dockerfile",
    "fish",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "graphql",
    "groovy",
    "html",
    "java",
    "javadoc",
    "javascript",
    "jq",
    "json",
    "json5",
    "jsonc",
    "kotlin",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nginx",
    "php",
    "phpdoc",
    "python",
    "rust",
    "sql",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  },
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "help" }, -- list of language that will be disabled
  },
}
