require("nvim-treesitter.configs").setup {
  ensure_installed = { 
    "angular",
    "awk",
    "bash",
    "c",
    "cpp",
    "css",
    "csv",
    "dap_repl",
    "dockerfile",
    "fish",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "html",
    "http",
    "javascript",
    ";xml",
    "jq",
    "json",
    "jsonc",
    "lua",
    "luap",
    "make",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "scheme",
    "scss",
    "sql",
    "toml",
    "typescript",
    "templ",
    "vim",
    "vimdoc",
    "vue",
    "yaml",
    "zig",
   },
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "help" }, -- list of language that will be disabled
  },
  matchup = {
    enable = true,
  },
}
